routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Lib\Payment;
use App\Models\ClientTranslationRequest;
use PhpParser\Node\Stmt\Return_;

Route::get('/test',function (\Illuminate\Http\Request $request){
    dd($request->all());
})->name('test');

Route::get('/payment',function (){
//     $payment = new Payment();
//     $red = $payment->CreateOrder(100);
// //    dd($red);
//     return redirect($red);
//     die;

    $invoice = ClientTranslationRequest::find(1);
    return view('emails.invoice',compact('invoice'));

});

Route::get('seen/{id}','NotificationsController@seen')->name('notifications.seen');
Route::get('clients_requests/download/{id}','DownloadController@downloadFile')->name('request.download');
Route::get('clients_requests/downloadTranslated/{id}','DownloadController@downloadTranslated')->name('request.downloadTranslated');

Route::post('webhook','DownloadController@webhook')->name('request.webhook');

Route::get('test_mail',function (){
    $invoice = ClientTranslationRequest::find(1);

    \Mail::send('emails.invoice', ['invoice'=>$invoice], function($message) {
        $message->to('ahmed.medo3061993@gmail.com')->subject('Testing mails');
    });
    \Mail::send('emails.notify_admin_new_request', [], function($message) use ($invoice) {
        $message->to('admin@trjim.com')->subject('New Request');
    });
});

//Admin
Route::group(['prefix'=>'admin','namespace'=>'Admin'],function (){
    //Auth Routes For Admin
    Route::get('login','Auth\LoginController@showLoginForm')->name('admin.showLogin');
    Route::post('login','Auth\LoginController@login')->name('admin.login');
    Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');
    Route::group(['middleware' =>'admin'],function(){

        Route::get('/','DashboardController@index')->name('admin.dashboard');
        Route::resource('packages','PackagesController');
        Route::resource('translators','TranslatorsController');
        Route::resource('subjects','SubjectController');
        Route::resource('users','UsersController');
        //Client Requests
        Route::get('clients_requests/{type?}','ClientsRequestsController@index')->name('admin.client_requests');
        Route::get('clients_requests/show/{id}','ClientsRequestsController@show')->name('admin.client_requests.show');
        Route::post('clients_requests/assign/{id}','ClientsRequestsController@assignTranslator')->name('admin.client_requests.assign');


    });
});


//Translator
Route::group(['prefix'=>'translator','namespace'=>'Translator'],function (){
    //Auth Routes For Admin
    Route::get('login','Auth\LoginController@showLoginForm')->name('translator.showLogin');
    Route::post('login','Auth\LoginController@login')->name('translator.login');
    Route::get('logout', 'Auth\LoginController@logout')->name('translator.logout');



    Route::group(['middleware' =>'translator'],function(){

        Route::get('/','DashboardController@index')->name('translator.dashboard');
        //Client Requests
        Route::get('clients_requests/{type?}','ClientsRequestsController@index')->name('translator.client_requests');
        Route::get('clients_requests/show/{id}','ClientsRequestsController@show')->name('translator.client_requests.show');
        Route::post('upload_translation','ClientsRequestsController@upload_translation')->name('translator.upload_translation');

    });

});


//Client
Route::group(['namespace'=>'Client','prefix' => LaravelLocalization::setLocale(),'middleware' => ['localeSessionRedirect', 'localizationRedirect']],function(){
    Auth::routes(['verify' => true]);

    Route::get('/','Auth\LoginController@showLoginForm');
    Route::post('login','Auth\LoginController@login')->name('client.login');
    Route::post('register','Auth\RegisterController@register')->name('client.register');
    Route::post('forget_password','ForgetPasswordController@SendForgetEmail')->name('client.forget_password');

    Route::get('currency_switch/{lang}','DashboardController@currency_switch')->name('switch_currency');
    Route::group(['middleware' =>'auth:web'],function(){
        Route::get('/logout','Auth\LoginController@logout')->name('client.logout');
        Route::get('clients','DashboardController@index')->name('clients.index');
        Route::get('change_password','ProfileController@ShowChangePassworForm')->name('clients.change_password');
        Route::post('submit_password','ProfileController@submit_password')->name('clients.submit_password');

        Route::resource('my_requests','ClientRequestsController');
        Route::get('show_requests/{type?}','ClientRequestsController@showRequests')->name('clients.show_requests');
        Route::post('get_languages','ClientRequestsController@get_languages')->name('clients.get_langs');
        Route::post('get_subjects','ClientRequestsController@get_subjects')->name('clients.get_subjects');
        Route::post('word_count','ClientRequestsController@word_count')->name('clients.word_count');
    });
});

app/Models/Subject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    //
    protected $fillable =['name','name_ar','name_zh'];

    public function getNameAttribute($value)
    {
        if(app()->getLocale() == 'en')
        {
            return $value;
        }else if (app()->getLocale() == 'ar')
        {
            return $this->name_ar;
        }else if (app()->getLocale() == 'zh')
        {
            return $this->name_zh;
        }else{
            return $value;
        }

    }
}

app/Http/Controllers/Admin/SubjectController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Subject;

class SubjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $subjects = Subject::all();
        return  view('admin.subjects.index',compact('subjects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.subjects.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $subject = new Subject();
        $subject->name = $request->name;
        $subject->save();

        return redirect()->route('subjects.index')->with('success','Subject Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $subject = Subject::find($id);
        return view('admin.subjects.form',compact('subject'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $subject = Subject::find($id);
        $subject->name = $request->name;
        $subject->save();

        return redirect()->route('subjects.index')->with('success','Subject Updated');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Subject::find($id)->delete();
        return redirect()->route('subjects.index')->with('success','Subject Deleted');

    }
}

resources/views/admin/subjects/form.blade.php
@extends('admin.layouts.master')
@section('title','Create Subjects')
@push('styles')

@endpush

@section('content')
    <div class="row">
        <div class="col-lg-12">

            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Subject
                        </h3>
                    </div>
                </div>

                <!--begin::Form-->
                {!! isset($subject) ? Form::model($subject,['url'=>route('subjects.update',[$subject->id]) , 'method'=>'PUT','class'=>'kt-form kt-form--label-right']) : Form::open(['route' => 'subjects.store', 'method' => 'post','class'=>'kt-form kt-form--label-right']) !!}

                <div class="kt-portlet__body">
                    <div class="form-group row">
                        <div class="col-lg-12">
                            {!! Form::label('Subject Name', 'Name', ['class' => 'control-label']) !!}
                            {!! Form::text('name' , null , ['class' => 'form-control ','requierd']) !!}
                        </div>
                    </div>
                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                        <div class="row">
                            <div class="col-lg-6">
                                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                            </div>
                            <div class="col-lg-6 kt-align-right">
                                <button type="reset" class="btn btn-secondary">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            {!! Form::close() !!}

            <!--end::Form-->
            </div>

            <!--end::Portlet-->
        </div>
    </div>

@endsection

@push('scripts')
    <script src="{{asset('assets/js/pages/crud/forms/widgets/select2.js')}}" type="text/javascript"></script>
@endpush

resources/views/admin/subjects/index.blade.php
@extends('admin.layouts.master')
@section('title','Subjects')
@push('styles')
    <link href="{{asset('assets/plugins/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endpush

@section('content')

    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <span class="kt-portlet__head-icon">
                    <i class="kt-font-brand flaticon2-line-chart"></i>
                </span>
                <h3 class="kt-portlet__head-title">
                    Subjects
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
                    <div class="kt-portlet__head-actions">
                        <a href="{{route('subjects.create')}}" class="btn btn-brand btn-elevate btn-icon-sm">
                            <i class="la la-plus"></i>
                            New subject
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="kt-portlet__body">

            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_3">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($subjects as $subject)
                    <tr>
                        <td>{{$subject->id}}</td>
                        <td>{{$subject->name}}</td>
                        <td>
                            <div class="row">
                                <div class="col-md-4">
                                    <a href="{{route('subjects.edit',$subject->id)}}" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="View">
                                        <i class="la la-edit"></i>
                                    </a>
                                </div>
                                <div class="col-md-4">
                                    <div class="col-md-6">
                                        <form action="{{route('subjects.destroy',$subject->id)}}" method="POST">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="delete">
                                            <button type="submit" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Delete"><i class="la la-remove"></i></button>
                                        </form>
                                    </div>
                                </div>
                            </div>


                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            <!--end: Datatable -->
        </div>
    </div>

@endsection

@push('scripts')
    <!--begin::Page Vendors(used by this page) -->
    <script src="{{asset('assets/plugins/custom/datatables/datatables.bundle.js')}}" type="text/javascript"></script>

    <!--end::Page Vendors -->

    <!--begin::Page Scripts(used by this page) -->
    <script src="{{asset('assets/js/pages/crud/datatables/data-sources/html.js')}}" type="text/javascript"></script>

    <!--end::Page Scripts -->

@endpush